version: 0.2

phases:
  install:
    #runtime-versions:
      #python: 3.8 
    commands:
      - echo Installing dependencies
  pre_build:
    commands:
      - echo Pre-building step

  build:
    commands:
      - echo Building the HTML project

  post_build:
    commands:
      - echo Uploading artifacts to S3
      #- mkdir build
      - ls -la
      #- zip -r artifact.zip . -x 'build/*'
      #- cp artifact.zip build/
      #- aws s3 cp ./build/ s3://code-build-deploy-bucket/ --recursive

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: yes
